# Generated by Django 4.2.5 on 2023-09-29 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название специализации')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор специализации')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.account')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Фрилансер',
                'verbose_name_plural': 'Фрилансеры',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет')),
                ('ask_budget', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('ask_deadline', models.BooleanField(default=False)),
                ('files', models.FileField(blank=True, null=True, upload_to='orders/job_files/', verbose_name='Файлы к заданию')),
                ('status', models.CharField(choices=[('Сбор заявок', 'Сбор заявок'), ('Сбор заявок завершен', 'Сбор заявок завершен')], max_length=20, verbose_name='Статус задания')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(help_text='Выберите специализацию', related_name='jobs', to='orders.category', verbose_name='Специализация')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название навыка')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.job')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='stack',
            field=models.ManyToManyField(help_text='Укажите стек технологий', related_name='jobs', to='orders.stack', verbose_name='Стек технологий'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='orders.stack'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.account'),
        ),
    ]
