# Generated by Django 4.2.5 on 2023-10-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobresponse',
            table=None,
        ),
    ]
