version: '3.1'
services:
  pg_db:
    image: postgres:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=100MB"
      - "-c"
      - "effective_cache_size=100MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=100MB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      - POSTGRES_PASSWORD=uyfuy^6jji
      - POSTGRES_USER=contract
      - POSTGRES_DB=contract
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_contract_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contract -d contract"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:
  pg_contract_data:

networks:
  main:
    external:
      name: external-contract-main