version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:16.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: taskiproject/freelancing-platform-project_backend:latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    links:
       - db:db
    env_file:
      - .env

  frontend:
    image: taskiproject/freelancing-platform-project_frontend:latest
    env_file: .env
    command: cp -r /app/result_build/. /static/
    volumes:
      - static:/static

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
