# Generated by Django 4.2.5 on 2023-10-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='industry',
            new_name='name',
        ),
    ]
