# Generated by Django 4.2.5 on 2023-10-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancereducation',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.education'),
        ),
        migrations.AlterField(
            model_name='freelancereducation',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workerprofile'),
        ),
    ]
