# Generated by Django 4.2.5 on 2023-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_industry_industry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(db_index=True, default='test', max_length=254, unique=True, verbose_name='публичный email address для связи'),
            preserve_default=False,
        ),
    ]
