# Generated by Django 4.2.5 on 2023-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_freelancereducation_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
