# Generated by Django 4.2.5 on 2023-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='публичный email address для связи'),
        ),
    ]
