# Generated by Django 4.2.5 on 2023-10-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='публичный email для связи'),
        ),
    ]
